server:
  port: ":8081"
  prefix: "/api/v1/gogo/driver"
database:
  dsn: "host=bytecub.home.lan port=30432 user=bytecub_admin password=UwBKsdysFkqIW3k dbname=bytecub sslmode=disable search_path=gogo"
