server:
  port: ":3000" # The single port your frontend will talk to
services:
  user:
    url: "http://localhost:8080"
    prefix: "/api/v1/gogo/user"
  driver:
    url: "http://localhost:8081"
    prefix: "/api/v1/gogo/driver"
  rides:
    url: "http://localhost:8082"
    prefix: "/api/v1/gogo/rides"